services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    expose:
      - 8096
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_DATA_DIR}/jellyfin:/config
      - /mnt:/mnt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOSTNAME}`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "flame.type=app"
      - "flame.name=Jellyfin"
      - "flame.url=https://${JELLYFIN_HOSTNAME}"
    depends_on:
      - rclone
    profiles:
      - jellyfin
      - debrid_media_server
      - all
