services:
  tweakio:
    image: varthe/tweakio:latest
    container_name: tweakio
    restart: unless-stopped
    # Run this container in the same network as warp, so it can access Torrentio
    # If not blocked by Torrentio, you can remove this line.
    # Will need to be accesssed at http://warp:3185 if using warp.
    network_mode: service:warp
    user: $PUID:$PGID
    volumes:
      - ${DOCKER_DATA_DIR}/tweakio/config.yaml:/app/config.yaml
    profiles:
      - all
      - debrid_media_server
      - tweakio
    depends_on:
      warp:
        condition: service_healthy
        restart: true
