services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1
    container_name: cloudflare-ddns
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    network_mode: host
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      PROXIED: false
      DOMAINS: >
        ${ADDON_MANAGER_HOSTNAME},
        ${AIOLISTS_HOSTNAME},
        ${AIOSTREAMS_HOSTNAME},
        ${AIOSTREMIO_HOSTNAME},
        ${ANIME_KITSU_HOSTNAME},
        ${ARCANE_HOSTNAME},
        ${AUTHELIA_HOSTNAME},
        ${AUTOSYNC_HOSTNAME},
        ${BAZARR_HOSTNAME},
        ${BAZARR4K_HOSTNAME},
        ${BESZEL_HOSTNAME},
        ${COMET_HOSTNAME},
        ${DASHDOT_HOSTNAME},
        ${DEBRIDAV_HOSTNAME},
        ${DECYPHARR_HOSTNAME},
        ${DOCKGE_HOSTNAME},
        ${DOZZLE_HOSTNAME},
        ${EASYNEWS_PLUS_HOSTNAME},
        ${EASYNEWS_PLUS_PLUS_HOSTNAME},
        ${HONEY_HOSTNAME},
        ${HUNTARR_HOSTNAME},
        ${JACKETT_HOSTNAME},
        ${JACKETTIO_HOSTNAME},
        ${JELLYFIN_HOSTNAME},
        ${JELLYSEER_HOSTNAME},
        ${LIBRESPEED_HOSTNAME},
        ${MEDIAFLOW_PROXY_HOSTNAME},
        ${MEDIAFUSION_HOSTNAME},
        ${MINECRAFT_HOSTNAME},
        ${NZBHYDRA2_HOSTNAME},
        ${OMG_TV_STREMIO_ADDON_HOSTNAME},
        ${OVERSEERR_HOSTNAME},
        ${PLAUSIBLE_HOSTNAME},
        ${PLEX_HOSTNAME},
        ${PORTAINER_HOSTNAME},
        ${PROWLARR_HOSTNAME},
        ${RADARR_HOSTNAME},
        ${RADARR4K_HOSTNAME},
        ${RADARRANIME_HOSTNAME},
        ${SEANIME_HOSTNAME},
        ${SEARXNG_HOSTNAME},
        ${SONARR_HOSTNAME},
        ${SONARR4K_HOSTNAME},
        ${SONARRANIME_HOSTNAME},
        ${SPEEDTEST_TRACKER_HOSTNAME},
        ${STREAMYSTATS_HOSTNAME},
        ${STREMIO_ACCOUNT_BOOTSTRAPPER_HOSTNAME},
        ${STREMIO_CATALOG_PROVIDERS_HOSTNAME},
        ${STREMIO_JACKETT_HOSTNAME},
        ${STREMIO_SERVER_HOSTNAME},
        ${STREMIO_TRAKT_ADDON_HOSTNAME},
        ${STREMTHRU_HOSTNAME},
        ${TAUTULLI_HOSTNAME},
        ${TMDB_ADDON_HOSTNAME},
        ${TORBOX_MANAGER_HOSTNAME},
        ${TRAEFIK_HOSTNAME},
        ${UPTIME_KUMA_HOSTNAME},
        ${VAULTWARDEN_HOSTNAME},
        ${YAMTRACK_HOSTNAME},
        ${ZILEAN_HOSTNAME},
        ${ZIPLINE_HOSTNAME},
        ${ZURG_HOSTNAME}
    profiles:
      - cloudflare-ddns
      - all
