services:
  bazarr:
    image: ghcr.io/hotio/bazarr
    container_name: bazarr
    restart: unless-stopped
    expose:
      - 6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-UTC}
    volumes:
      - ${DOCKER_DATA_DIR}/bazarr/default/config:/config
      - ${DOCKER_DATA_DIR}/bazarr/default/data:/data
      - /mnt:/mnt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`${BAZARR_HOSTNAME?}`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    profiles:
      - all
      - bazarr
      - debrid_media_server
    depends_on:
      - rclone
      - sonarr
      - radarr


  bazarr4k:
    image: ghcr.io/hotio/bazarr
    container_name: bazarr4k
    restart: unless-stopped
    expose:
      - 6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-UTC}
    volumes: 
      - ${DOCKER_DATA_DIR}/bazarr/4k/config:/config
      - ${DOCKER_DATA_DIR}/bazarr/4k/data:/data
      - /mnt:/mnt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr4k.rule=Host(`${BAZARR4K_HOSTNAME?}`)"
      - "traefik.http.routers.bazarr4k.entrypoints=websecure"
      - "traefik.http.routers.bazarr4k.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bazarr4k.middlewares=authelia@docker"
      - "traefik.http.services.bazarr4k.loadbalancer.server.port=6767"
    profiles:
      - all
      - bazarr
      - debrid_media_server
    depends_on:
      - rclone
      - sonarr4k
      - radarr4k
