include:
  - authelia/compose.yaml
  - addon-manager/compose.yaml
  - arcane/compose.yaml
  - aiostreams/compose.yaml
  - aiostremio/compose.yaml
  - anime-kitsu/compose.yaml
  - autosync/compose.yaml
  - bazarr/compose.yaml
  - beszel/compose.yaml
  - byparr/compose.yaml
  - cloudflare-ddns/compose.yaml
  - comet/compose.yaml
  - dash/compose.yaml
  - debridav/compose.yaml
  - decypharr/compose.yaml
  - dockge/compose.yaml
  - dozzle/compose.yaml
  - easynews-plus/compose.yaml
  - easynews-plus-plus/compose.yaml
  - gluetun/compose.yaml
  - honey/compose.yaml
  - huntarr/compose.yaml
  - jackett/compose.yaml
  - jackettio/compose.yaml
  - jellyfin/compose.yaml
  - jellyseer/compose.yaml
  - kometa/compose.yaml
  - librespeed/compose.yaml
  - mediaflow-proxy/compose.yaml
  - mediafusion/compose.yaml
  - minecraft/compose.yaml
  - nzbhydra2/compose.yaml
  - omg-tv-addon/compose.yaml
  - overseerr/compose.yaml
  - plausible/compose.yaml
  - plex/compose.yaml
  - plex-trakt-sync/compose.yaml
  - portainer/compose.yaml
  - prowlarr/compose.yaml
  - radarr/compose.yaml
  - realdebrid-account-monitor/compose.yaml
  - recyclarr/compose.yaml
  - seanime/compose.yaml
  - searxng/compose.yaml
  - sonarr/compose.yaml
  - speedtest-tracker/compose.yaml
  - sshbot/compose.yaml
  - streamystats/compose.yaml
  - stremio-account-bootstrapper/compose.yaml
  - stremio-catalog-providers/compose.yaml
  - stremio-jackett/compose.yaml
  - stremio-server/compose.yaml
  - stremio-trakt-addon/compose.yaml
  - stremthru/compose.yaml
  - tautulli/compose.yaml
  - tmdb-addon/compose.yaml
  - torbox-manager/compose.yaml
  - torbox-media-center/compose.yaml
  - traefik/compose.yaml
  - tweakio/compose.yaml
  - uptime-kuma/compose.yaml
  - vaultwarden/compose.yaml
  - warp/compose.yaml
  - watchtower/compose.yaml
  - wests-scripts/compose.yaml
  - yamtrack/compose.yaml
  - zilean/compose.yaml
  - zipline/compose.yaml
  # Uncomment if you are using zurg and comment out decypharr
  # There is also a way to use both together, but it requires 2 rclone instances
  # To use both, update Zurg's rclone service name and its container name to rclone_zurg
  # You will also need to change Zurg's rclone's `- /mnt/remote/realdebrid:/data:rshared` to `- /mnt/remote/zurg:/data:rshared`
  # - zurg/compose.yaml

networks:
  default:
    name: ${DOCKER_NETWORK:-aio_default}
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
